### PR TITLE
Make handling the timetable-or extension consistent.

### PR DESCRIPTION
**Pull request by pzgulyas**
Bug report https://bugs.launchpad.net/or/+bug/1958064

### CODE REVIEW

**Comment by Sharpe49** [comment]
Code seems good.
Please refer to a bug report.

**Comment by pzgulyas** [comment]
By the [Open Rails Triage](https://github.com/openrails/openrails-triage) this change fulfills the following category:
<= 10 additions and <= 10 deletions - small changes are allow to bypass normal rules

**Comment by Sharpe49** [comment]
That's the rules that the triage tool uses to work.

The rules for contribution are here: https://github.com/openrails/openrails/blob/master/Docs/Contributing.md

**Comment by pzgulyas** [comment]
@cjakeman, @twpol, could you please explain the reason of discrepancy between the two above linked descriptions?

**Comment by Sharpe49** [comment]
@pzgulyas @cjakeman @twpol Any news about the question above?

**Review by cjakeman — APPROVED** [review]
Hi Peter,

Thanks for this small and importnat bug-fix.

To comply with our review process, I've added a bug report to Launchpad.net/or and referenced it in the initial comment.

Approved.

Chris

**Comment by cjakeman** [comment]
> @cjakeman, @twpol, could you please explain the reason of discrepancy between the two above linked descriptions?

Sharpe49 is correct.

The Open Rails Triage delivers a report on current submissions to James. I don't think it takes any actions.

Peer reviewers should follow the rules in Contributing.md

Hope that helps,

Chris

**Pull request merged**
