### PR TITLE
Fixed delayed opening of signals on high speed lines in explorer mode https://bugs.launchpad.net/or/+bug/1613304

### PR DESCRIPTION
**Pull request by Sharpe49**
And also a bit of refactoring

### CODE REVIEW

**Comment by YoRyan** [comment]
From your comment on the bug report,
> Increasing the distance value won't solve the problem. As in the activity mode, we need to use the SignalNumClearAhead variable to know how much signals must be opened in front of our train.

But if I'm reading your diff right, your fix is to replace `minCheckDistanceM` with `Math.Max(AllowedMaxSpeedMpS * maxTimeS, minCheckDistanceM)` - ergo, increasing the distance. Can you explain how this interacts with the `SignalNumClearAhead` property?

**Comment by Sharpe49** [comment]
Look at the date of the bug report, it says 2016. :)
I have looked at this problem again a few days ago.

I think this is happening : 
- The simulator class asks for an update of the trains
- The train class reserves the path for 5 km only due to the way the code I just fixed is working
- The simulator class then asks for an update of the signals
- The signals are updated according to the SNCA parameter... but since the path is not reserved beyond 5 km, the route_set() condition is not true and the signals after 5 km are not opening.

**Comment by Sharpe49** [comment]
I am also currently running some tests : I may have to increase the maxTimeS parameter to 3 minutes (only on high speed lines).

**Comment by Sharpe49** [comment]
I have probably a better idea : instead of saying "if the allowed speed is above 250 kph, then the max time is 3 minutes, otherwise, it is 2 minutes."
These parameters can be modified... in the TCS script. I'll try this.

**Comment by YoRyan** [comment]
I would not advise this. High speed routes should just work, whether or not a TCS script is present.

What's the upper bound on the maximum check distance and time? Is it just the computation time?

**Comment by Sharpe49** [comment]
What do you mean ? In real life ?

**Comment by YoRyan** [comment]
Sorry - I mean, so far as you can tell, is there any reasoning behind the 5km limit? What if we simply increased it so that more signals will be able to clear?

**Comment by Sharpe49** [comment]
I don't think there is a reasoning behind this value.
If we increase it too much, we may deadlock other routes too soon.

Perhaps I can try this :
- Get SNCA value for next signal
- Find the distance to nth signal according to SNCA value
- Reserve track for this distance.

**Comment by YoRyan** [comment]
Yes, that sounds like a reasonable approach.

I don't know much about the signal system myself - so don't feel the need to follow my suggestions - but I hope we can find a solution that doesn't depend on increasing some arbitrary distance.

**Comment by Sharpe49** [comment]
The last commit contains a rebase and a refactoring of the check distance in the Signals.cs file.

Next change incoming is the new algorithm described above.

**Comment by Sharpe49** [comment]
Finally, I managed to make it work properly on my side.
Ready to be tested and reviewed.

**Comment by cjakeman** [comment]
> Thanks; it looks good to me. Maybe we leave it in unstable for another week or two and see if we get any reports of odd signal behavior.

It's had long enough now, I think.

Approved with thanks,

Chris

**Comment by YoRyan** [comment]
Unfortunately, we now have a [bug report](http://www.elvastower.com/forums/index.php?/topic/34297-mg71-crash-index-was-out-of-range-must-be-non-negative-and-less-than-the-size-of-the-collection/) related to this change.

Full traceback:

```
Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Orts.Simulation.Signalling.Signals.ScanRoute(Train thisTrain, Int32 firstSectionIndex, Single firstOffset, Int32 firstDirection, Boolean forward, Single routeLength, Boolean honourManualSwitch, Boolean autoAlign, Boolean stopAtFacingSignal, Boolean reservedOnly, Boolean returnSections, Boolean searchFacingSignal, Boolean searchBackwardSignal, Boolean searchFacingSpeedpost, Boolean searchBackwardSpeedpost, Boolean isFreight, Boolean considerSpeedReset, Boolean checkReenterOriginalRoute) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Signalling\Signals.cs:line 3941
   at Orts.Simulation.Physics.Train.get_CheckDistanceM() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Physics\Train.cs:line 285
   at Orts.Simulation.Physics.Train.CheckRealDeadlock_locationBased(TCSubpathRoute thisRoute, TCSubpathRoute otherRoute, Int32& elementIndex) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Physics\Train.cs:line 12419
   at Orts.Simulation.Physics.Train.CheckDeadlock_locationBased(TCSubpathRoute thisRoute, Int32 thisNumber) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Physics\Train.cs:line 11973
   at Orts.Simulation.Physics.Train.CheckDeadlock(TCSubpathRoute thisRoute, Int32 thisNumber) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Physics\Train.cs:line 11727
   at Orts.Simulation.AIs.AITrain.PostInit() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\AIs\AITrain.cs:line 411
   at Orts.Simulation.AIs.AI.AddToWorld(AITrain thisTrain) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\AIs\AI.cs:line 977
   at Orts.Simulation.AIs.AI.AIUpdate(Single elapsedClockSeconds, Boolean preUpdate) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\AIs\AI.cs:line 663
   at Orts.Simulation.AIs.AI.PrerunAI(CancellationToken cancellation) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\AIs\AI.cs:line 353
   at Orts.Simulation.AIs.AI..ctor(Simulator simulator, CancellationToken cancellation, Double activityStartTime) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\AIs\AI.cs:line 94
   at Orts.Simulation.Simulator.InitializeAPTrains(CancellationToken cancellation) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Simulator.cs:line 600
   at Orts.Simulation.Simulator.Start(CancellationToken cancellation) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\Orts.Simulation\Simulation\Simulator.cs:line 465
   at Orts.Viewer3D.Processes.GameStateRunActivity.Start(UserSettings settings, String acttype, String[] options, String[] args) in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\GameStateRunActivity.cs:line 300
   at Orts.Viewer3D.Processes.GameStateRunActivity.<>c__DisplayClass35_0.<Load>b__3() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\GameStateRunActivity.cs:line 162
   at Orts.Viewer3D.Processes.GameStateRunActivity.Load() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\GameStateRunActivity.cs:line 203
   at Orts.Viewer3D.Processes.LoaderProcess.Load() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\LoaderProcess.cs:line 159
   at Orts.Viewer3D.Processes.LoaderProcess.DoLoad() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\LoaderProcess.cs:line 138
   at Orts.Viewer3D.Processes.LoaderProcess.LoaderThread() in F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Processes\LoaderProcess.cs:line 109
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Pull request merged**
