### PR TITLE
Steam adhesion not applied to all locomotives in the player train.

### PR DESCRIPTION
**Pull request by peternewell**
See this thread for more details -

Bug report - https://bugs.launchpad.net/or/+bug/1950408

http://www.elvastower.com/forums/index.php?/topic/35337-curtius-kniffler-adhesion-parameter/page__view__findpost__p__277792

### CODE REVIEW

**Review by Csantucci — COMMENTED** [review]
In the comment below your correction in MSTSSteamLocomotive.cs you write:
"and is the player locomotive"
Accordingly to your fix I'd expect that this comment should be modified.

**Comment by peternewell** [comment]
> 
> 
> In the comment below your correction in MSTSSteamLocomotive.cs you write: "and is the player locomotive" Accordingly to your fix I'd expect that this comment should be modified.

Thanks for picking that up. Corrected as suggested.

**Review by Sharpe49 — APPROVED** [review]

**Comment by Sharpe49** [comment]
You need to add a link to a bug report.

**Comment by peternewell** [comment]
Thanks for approving this.

**Pull request merged**
