### PR TITLE
Timetable trains shown on a map v2

### PR DESCRIPTION
**Pull request by cjakeman**
https://blueprints.launchpad.net/or/+spec/timetable-window

Adds a tab to the map window which shows the timetabled trains with their HUD values and signals info. Useful for players and timetable creators. Prototype tested by Rick Loader on a very large timetable.

Manual updated (7.5.2 Timetable Tab)

The code piggy-backs off the dispatch window. I've tried hard to leave as much of that code unchanged as possible since it has lots of functions including multi-player that I am not competent to test thoroughly.

The graphics look a bit better because:

    anti-aliasing is used
    platforms are visible
    locos are shown in a different colour
    the lead vehicle is a different colour so the direction of a train is obvious
    objects and their labels can be shown or hidden

This is a copy of PR 282 because I cannot resolve the conflicts reported by the Code Bot.

For reasons explained by Ryan below (Nov 5), this is held as a DRAFT as it has to wait for #230 Monogame to be merged into the master  (Testing version). 
Taken out of DRAFT 27-Feb-21

### CODE REVIEW

**Comment by Csantucci** [comment]
I get errors trying to build the Unstable release, and in effect the Unstable releases of today don't appear.
I get 8 errors like this one
Error	CS0104	'Color' is an ambiguous reference between 'System.Drawing.Color' and 'Microsoft.Xna.Framework.Color'	RunActivity	F:\ADRIANA\Carlo\OR_Work\Git_ORTS_source_mio\Source\RunActivity\Viewer3D\Debugging\TimetableWindow.cs	750	Active

By adding on top of TimetableWindow.cs this line 
using Color = System.Drawing.Color;
like you did in DebugViewerForm.cs
the errors disappear.

**Comment by YoRyan** [comment]
Thanks, Chris. This new version looks nearly ready to merge. I just have some concerns about `Source/RunActivity/Viewer3D/Debugging/TimetableWindow.cs`; it still has some inconsistent indentation, which we should try to avoid in brand-new files. Please see the attached patch for your consideration.
[fix-indentation.patch.txt](https://github.com/openrails/openrails/files/5489571/fix-indentation.patch.txt)

**Comment by Csantucci** [comment]
Ryan,
please see my message just before yours.

**Comment by YoRyan** [comment]
Oops. Carlo, I concur with you. @cjakeman's branch builds just fine, but it looks like it doesn't merge cleanly into the unstable release.

Since this PR touches the graphics code, it may have to wait until #230 is merged.

**Comment by cjakeman** [comment]
Hi Ryan,

Carlo reports:
> By adding on top of TimetableWindow.cs this line
> using Color = System.Drawing.Color;
> like you did in DebugViewerForm.cs
> the errors disappear. 

But you write:
> Oops. Carlo, I concur with you. @cjakeman's branch builds just fine, but it looks like it doesn't merge cleanly into the unstable release.
> 
> Since this PR touches the graphics code, it may have to wait until #230 is merged.

Surely, if I add that extra line (and fix the indentation - thanks) then it will become compatible with #230. Or am I missing something?

Chris

**Comment by Csantucci** [comment]
Hi Chris,
if you add that line (as you already did for another file) you should solve problems.

**Comment by YoRyan** [comment]
Just tried it. It works when you merge the code into unstable, but it breaks the build for the testing branch, because the current code expects a `Microsoft.Xna.Framework.Graphics.Color`, not a `System.Drawing.Color`. And if you use `using Color = Microsoft.Xna.Framework.Graphics.Color`, that works for the testing branch, but breaks the Monogame PR, because that assembly no longer exists in Monogame.

So unfortunately, I don't see a way to merge this in before #230.

**Comment by cjakeman** [comment]
Thanks for researching this, Ryan.

We'll just have to be patient !

**Comment by Csantucci** [comment]
Chris and Ryan,
sorry for my last info, that was wrong.
Chris,
Timetable trains map v1 is present in OR NY MG.

**Comment by YoRyan** [comment]
Chris, feel free to brush up this PR and take it out of draft now that #230 is merged. 😊

**Comment by cjakeman** [comment]
Hi Ryan,

> Chris, feel free to brush up this PR and take it out of draft now that #230 is merged. 😊

Will do. In fact was adding some refinements this weekend. Should be there soon.

Chris

**Review by YoRyan — APPROVED** [review]
Well done, Chris. It's been a long road, but this looks ready to merge after a quick `dotnet format`.

**Pull request merged**
