### PR TITLE
Upgraded project files to .Net SDK project file format

### PR DESCRIPTION
**Pull request by Sharpe49**
Removed AssemblyInfo files (integrated in the project file)
Removed unused files (not referenced in the old project files)
Removed resource files in ActivityEditor which were causing execution problems

1st step of https://blueprints.launchpad.net/or/+spec/dependencies-update
http://www.elvastower.com/forums/index.php?/topic/32819-upgrading-net-c/page__view__findpost__p__278324

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi Cedric,

The Code Bot at https://james-ross.co.uk/projects/or reports a merge/delete conflict for Source/Orts.Simulation/packages.config 

Are you able to sort this out?

Thanks,

Chris

**Comment by Sharpe49** [comment]
That's to be expected. The packages.config will be deleted (its information are now integrated in the csproj file) while another pull request wants to modify the packages.config file (it should be the script compiler pull request).

**Comment by Sharpe49** [comment]
Ok, rebased my branch and taking it out of draft.

**Comment by Sharpe49** [comment]
Unstable builds are failing because other branches are adding files to the csproj files, which is forbidden.

**Comment by Sharpe49** [comment]
I prefer rebasing instead of merging when we are in a branch. It makes the history easier to understand.

**Review by cjakeman — APPROVED** [review]
Hi Cedric,

This is large piece of work and I can't say I know enough to criticise it.

However it's been around long enough for any issues to show up so I'm approving and merging it.

Many thanks,

Chris

**Pull request merged**
