### PR TITLE
Pop to front

### PR DESCRIPTION
**Pull request by cjakeman**
Change WindowState from minimized to normal so DispatchWindow appears in front of graphic window, not behind.

https://blueprints.launchpad.net/or/+spec/dispatch-window-on-top

Was tried once before but didn't work on Monogame. This version does.

### CODE REVIEW

**Comment by YoRyan** [comment]
Hi Chris,

This change doesn't seem to work for me. My dispatcher window still starts minimized. Is your PR missing a hunk or two?

**Comment by cjakeman** [comment]
Maybe. I'll have a look tomorrow.

Thanks.

**Comment by cjakeman** [comment]
Hi Ryan,

I think I've fixed it, but would be helpful if you can try it on your own PC.

Thanks,

Chris

**Comment by cjakeman** [comment]
Oops. Didn't mean to add this "added controls for timetable-window here, so I've reverted it

**Comment by YoRyan** [comment]
Hi Chris,

Yes, this now tests correctly for me. I think the probability of any breakage is quite unlikely, so I shall merge this immediately.

**Pull request merged**
