### PR TITLE
Switch panel (web based) enhancements

### PR DESCRIPTION
**Pull request by sweiland-openrails**

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi Siebren,

Can you provide a link to a Blueprint or a Trello card for this enhancement, please?

Thanks,

Chris

**Comment by sweiland-openrails** [comment]
hi Chris  ( @cjakeman ),

sure I can create one. Can you tell me what's the difference between a Trello card and Blueprint?  Does it has to do with a PR containing an enhancement of a bugfix? This PR contains two changes: a  bugfix and an enhancement. I can create two PR's instead of this one. No problem.

regards, Siebren.

**Comment by cjakeman** [comment]
Hi Siebren,

> Can you tell me what's the difference between a Trello card and Blueprint? Does it has to do with a PR containing an enhancement of a bugfix? 

For enhancements, Trello cards and Blueprints are alternatives and the choice is yours.
Trello cards can be voted on so developers can see what the community values most. They are very simple.
Blueprints provide a more structured way for everyone to monitor the development process, so are suitable for larger features.

By the way, we still plan to move the Bug Reporting from Launchpad.net to Github. 

> This PR contains two changes: a bugfix and an enhancement. I can create two PR's instead of this one. 

It's best to keep them separate if they really are independent.

Best wishes,

Chris

**Comment by sweiland-openrails** [comment]
to be closed without merge, this PR has been split into two

**Pull request closed without merging**
