### PR TITLE
Improve memory statistics for CPU and GPU

### PR DESCRIPTION
**Pull request by twpol**
Feature request: Missing (please add Elvas Tower, Trello, Launchpad link if one exists)

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi James,

Nice to see this.

Will you be updating the section in the Manual on HUD Display to match? (I wonder if that should go into a separate chapter on Debug Tools?)

Best wishes,

Chris

**Comment by twpol** [comment]
> Will you be updating the section in the Manual on HUD Display to match? (I wonder if that should go into a separate chapter on Debug Tools?)
The section was quite bare, so I've expanded it to explain all the values and included an example of how you might check performance

**Comment by cjakeman** [comment]
> The section was quite bare, so I've expanded it to explain all the values and included an example of how you might check performance

I can see how very bare it was from the new material you've added. Good job.

**Review by cjakeman — APPROVED** [review]
HI James,

Approved with thanks,

Chris

**Pull request merged**
