### PR TITLE
notrriggered => nottriggered x 2

### PR DESCRIPTION
**Pull request by cjakeman**
Corrected spelling errors in Parser for activities found by John (RR1)

### CODE REVIEW

**Comment by YoRyan** [comment]
Looks good

**Review by YoRyan — DISMISSED** [review]

**Comment by YoRyan** [comment]
So, what's the history behind this property? Is it a custom ORTS one, or does the MSTS Activity Editor output `texttodisplayoncompletionifnotrriggered`?

If the latter is the case, then we need to retain support for the misspelling to retain backwards compatibility with MSTS.

**Comment by Sharpe49** [comment]
I did a search inside my activity files, it is spelled TextToDisplayOnCompletionIfNotTriggered.
So the fix is correct.

**Review by Sharpe49 — APPROVED** [review]

**Comment by YoRyan** [comment]
Perfect. Thanks for checking, Cedric.

**Pull request merged**
