### PR TITLE
Consolidated wind simulation #or-environment

### PR DESCRIPTION
**Pull request by twpol**
Roadmap: https://trello.com/c/ZBk5lhbl/578-consolidate-weather-simulation-into-a-single-place
Discussion: http://www.elvastower.com/forums/index.php?/topic/34984-build-a-better-skydome-terragen-2/

This PR merges all the separate winds into a single one, with average and instantaneous speed and directions (normal and gusts)

- [x] Clean up simulation wind
- [x] Make clouds respond correctly to wind
- [x] Make particles respond correctly to wind
- [x] Make precipitation respond correctly to wind

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi James,

Is there a Blueprint or a Trello card yet for this work?

- Who will be affected? (E.g. all users, some users, devs?)
- How will they be affected? (E.g. new option/control/change to content files?)
- What risks will there be? (E.g. any other code affected, performance implications?)
- Are examples needed?

Thanks,

Chris

**Comment by cjakeman** [comment]
Hi James,

I've added the "not-for-unstable" label as this long-running PR conflicts with PR 857. Both PRs add a short method at the same point in the file Conversions.cs

The intention is to approve and merge 857 as soon as possible, so that you can merge the change back in from the master and get your PR back into the Unstable Version.

Hope that's OK,

Chris

**Comment by SteelFill** [comment]
Took some time to get the air flow meters sorted but now that's merged the flow meters and wind can coexist. There's just the conflict in Conversions.cs, which seems to be dumb luck as both additions are entirely different but just so happened to be placed in the same location.

**Comment by cjakeman** [comment]
Label changed to not-for-unstable temporarily to hide changes to UserSettings.cs to let other PRs merge into Unstable

**Comment by cjakeman** [comment]
And restored again

**Review by cjakeman — APPROVED** [review]
Hi James,

Very thorough. No issues.
Approved and merged.

Thanks,

Chris

**Pull request merged**
