### PR TITLE
Blueprint https://blueprints.launchpad.net/or/+spec/multiple-screen-pages in 2D and 3D cabs

### PR DESCRIPTION
**Pull request by Csantucci**
See http://www.elvastower.com/forums/index.php?/topic/35612-managing-multiple-screen-pages-on-a-display-in-2d-and-3d-cabs/

### CODE REVIEW

**Review by pzgulyas — APPROVED** [review]
No obvious error hits my eyes, I find it all right.

**Comment by Csantucci** [comment]
Hi Peter,
thank you also here! This PR  clashed with my other one, because they intervene in the same files, so, now that the other one is merged, I had to update this one. Therefore I am kindly asking you to approve it again.

**Review by pzgulyas — APPROVED** [review]
Seems okay!

**Comment by Csantucci** [comment]
Wow, that was fast! :)

**Pull request merged**
