### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by Weter-ORTS**
Some new strings translated
Some corrected via testing

### CODE REVIEW

**Comment by YoRyan** [comment]
Thanks, Weter; all looks good. Let us know when you are ready to merge.

**Review by YoRyan — APPROVED** [review]

**Comment by Weter-ORTS** [comment]
I ask to excuse me, but it needs to be cleared for me about GitHub order:
Since I uploaded modified files, they were verified by mashine and then-by experienced reviewer(s)
Then, I usualy asked something like: "Tell us, when You'll be ready"
What should I do with given PR else, before say: "Yes, I'm ready"?
Thanks.

**Comment by YoRyan** [comment]
You can mark your pull request as "draft" to indicate to us that you're not yet finished with your changes. If you don't do this, we're going to assume that it's ready to be reviewed and merged as-is.

However, I've asked if you're "ready to merge" because I've noticed you have a habit of submitting multiple batches of changes. To help clarify the status of future PR's, it would be a big help if you could use the draft function.

**Comment by Weter-ORTS** [comment]
Respectable Ryan, I live that way, as every visit of GitHub or the whole I-net, may be the last for me, so every file, I place here cAn be used further, because perfection is often unreachable and I still can't understand the context of couple dozens of short strings.
I trying to upload materials, that I hAve tested at least once... but who knows, maybe few days later, continious thinking, about how ORST working, would give me some better ideas...
Thank For answering and specially-foe tip about Draft.

**Comment by Weter-ORTS** [comment]
P.S.
Pitty, it seems, no one, who could test new translation, uses Unstable versions of ORTS (furthermore, testing-too), so I'm "investing" to distant, undefined future.

**Comment by YoRyan** [comment]
Apologies, I may have come across as needlessly harsh. It's certainly not your fault that you don't know every feature of the GitHub interface. You are, after all, not a software developer.

**Comment by Weter-ORTS** [comment]
Never mind :)
The problem is not Your words, but that thing, that I have none I-net for last 10 years; gain it now ocassionally only (need to work distant - You can guess, why), and no one knows, what will happen tomorrow.

**Comment by YoRyan** [comment]
To be clear, using the draft feature isn't a hard "rule" either; it's just an unambiguous way for us to communicate the statuses of pull requests.

...You really have no regular Internet connection? Not even a smartphone you could tether your computer off of, or browse the Internet with?

**Comment by Weter-ORTS** [comment]
Didn't needed more, than check for updates one time per season (i've lost my E-mail about 4 years ago)
But that was for MSTS-content updates, but OPEN rails,,, I've appreciated the work done by the Team and used this circumstances to improve its international capabilities.

**Review by Weter-ORTS — COMMENTED** [review]
The mistake was found and processed.
The conflict-resolved/
Check passed.

**Comment by Weter-ORTS** [comment]
Added translation for Map Window text, TrainBrake's position names corrected.

**Comment by YoRyan** [comment]
Okay, so is this ready to merge, or do you still need to work on the strings made newly translatable by #376?

**Comment by Weter-ORTS** [comment]
If #376 is included to source, I only will be able to use it.
Other is satisfying, so we can proceed.
Then, update with other.

**Comment by Weter-ORTS** [comment]
I've finally DONE that :)
Testing...

**Review by YoRyan — APPROVED** [review]
Right then, let's mark this ready to go!

As always, Weter, thank you very much for your contributions.

**Comment by Weter-ORTS** [comment]
Thank You too, Ryan, and, please don't be cross on me - I've never wanted to say anything offensive at your address.
The work is continued.

**Pull request merged**
