### PR TITLE
Update version calculation for new unstable versions

### PR DESCRIPTION
**Pull request by twpol**
Discussion: http://www.elvastower.com/forums/index.php?/topic/33183-automatic-inclusion-of-open-pull-requests-in-unstable-version/

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi James,

> Discussion: http://www.elvastower.com/forums/index.php?/topic/33183-automatic-inclusion-of-open-pull-requests-in-unstable-version/
> 
> **DO NOT MERGE YET**

Does this message "DO NOT MERGE YET" still apply? Or can I merge the PR?

Thanks,

Chris

**Comment by twpol** [comment]
> Does this message "DO NOT MERGE YET" still apply? Or can I merge the PR?

I have not yet confirmed that this code does the right thing for the Testing or Stable Versions; it is only for Unstable currently and may need further changes.

I'll have a look at this soon.

**Comment by twpol** [comment]
Ready for this to be reviewed

**Review by cjakeman — APPROVED** [review]
Not able to test this, so I'm taking it on trust.

**Pull request merged**
