### PR TITLE
Menu option04 - invert controls

### PR DESCRIPTION
**Pull request by cjakeman**
See https://blueprints.launchpad.net/or/+spec/update-menu-options
and http://www.elvastower.com/forums/index.php?/topic/35301-menu-options

"Disable TCS Scripts" => "Use TCS Scripts"
"Diesel engines stopped after startup" => "At game start, Diesel - run engines"

This PR changes the UI, but not the defaults and the user's settings are preserved too.

### CODE REVIEW

**Comment by Weter-ORTS** [comment]
> At game start, Diesel - run engines
Internal combustion engines running at game start

**Comment by cesarBLG** [comment]
Hi Chris,
Is there a reason for changing the UI, but not the internal variable naming?
For example, could Settings.DisableTCSScripts be changed to Settings.EnableTCSScripts, so there's a correspondence between UI and code?

**Comment by cesarBLG** [comment]
Hi Chris,
Is there a reason for changing the UI, but not the internal variable naming?
For example, could Settings.DisableTCSScripts be changed to Settings.EnableTCSScripts, so there's a correspondence between UI and code?

**Comment by cjakeman** [comment]
Hi Cesar,

Thanks for looking at this.

I agree that it's not ideal, but I didn't do as you suggest in order to keep the user's saved settings.
The current PR does not require the user to do anything. If his "Disable TCS" was checked then his new "Enable TCS" will be unchecked. 

Chris

**Review by cesarBLG — APPROVED** [review]
I see, in that case it's OK to me.

**Pull request merged**
