### PR TITLE
Dispatcher window improvements

### PR DESCRIPTION
**Pull request by Looky1173**
This PR reworks the interface of the Dispatcher window as outlined on ElvasTower

Feature request: https://www.elvastower.com/forums/index.php?/topic/37165-reworking-the-dispatcher-window/

The "beta" Dispatcher window can be accessed in-game by pressing `Ctrl + Shift + 9`

### CODE REVIEW

**Comment by Looky1173** [comment]
@cjakeman @twpol Hi, could the "for-unstable" label be added to this PR please? See [this post](http://www.elvastower.com/forums/index.php?/topic/37165-reworking-the-dispatcher-window/page__view__findpost__p__299871) for more information about this PR.

**Comment by cjakeman** [comment]
Hi Gergely,

I don't see a Trello card for this change so, when you're ready, would you create one please and add a link in your first post above.
Then I can approve it.

Thanks,

Chris

**Comment by Looky1173** [comment]
Hi Chris,

I created a Trello card for these changes. I have renamed `DispatchViewerBeta` to `MapView` too.

I'm still having trouble with translation though. Whatever I do, the strings I translated in Poedit are still English in-game. Could you please tell me which `.bat` files I have to run in the _Locales_ folder, and in what order?

Thank you,
Gergely

**Comment by cjakeman** [comment]
> I created [a Trello card](https://trello.com/c/baw9oAsE/574-redesign-the-map-window) for these changes. I have renamed `DispatchViewerBeta` to `MapView` too.

Thanks. And I've approved the card by moving it to the v1.6 stack.

> I'm still having trouble with translations though. Whatever I do, the strings I translated in Poedit stay English in-game. Could you please tell me which `.bat` files I have to run in the _Locales_ folder, and in what order?

I don't know straight away. I'll look into it. If I can't sort it out, we can always ask James.

Best wishes,

Chris

**Comment by cjakeman** [comment]
Hi Gergely,

> > I'm still having trouble with translations though. Whatever I do, the strings I translated in Poedit stay English in-game. Could you please tell me which `.bat` files I have to run in the _Locales_ folder, and in what order?

I've managed to make this work in-game and in the MapForm - see my ET posts starting with [http://www.elvastower.com/forums/index.php?/topic/37165-reworking-the-dispatcher-window/page__view__findpost__p__301402](http://www.elvastower.com/forums/index.php?/topic/37165-reworking-the-dispatcher-window/page__view__findpost__p__301402) 

Hope that works for you too.

Sorry to take so long and best wishes,

Chris

**Comment by cjakeman** [comment]
Hi Looky,

Pleased that you've been able to get the translations working. 

> The "beta" Dispatcher window can be accessed in-game by pressing `Ctrl + Shift + 9`

Is it time now to change this PR to activate the new window with Ctrl + 9 and to remove the old window.

Is there anything else outstanding that would stop the PR being approved and merged into the master branch?

Best wishes,

Chris

**Comment by twpol** [comment]
> No, except that translations do not work with dropdown menus (ContextMenuStrip), and I can't find anything online for why should this be. It could be that the library we are using doesn't handle such dropdowns, in which case I could localize all dropdown items individually with `Viewer.Catalog.GetString()`. Not ideal, but it would work at least. What do you think?

That seems unfortunate; the strings are being found, so it seems to be a failure to apply them in `GNU.gettext` rather than anything wrong with your code.

We (ORMT) are okay with using `Viewer.Catalog.GetString()` to manually apply them for now.

**Comment by Looky1173** [comment]
I replaced the legacy Dispatch window with the new `MapViewer`, and this PR is now ready for review.

**Review by cjakeman — APPROVED** [review]
Hi Gergely,

Thanks for making these final changes.

All approved and merged now.

Chris

**Pull request merged**
