### PR TITLE
Wheel creep model for steam locomotives

### PR DESCRIPTION
**Pull request by cesarBLG**
Second part of PR #627. Divided to make reviewing easier. Not yet usable.

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi Cesar,

Now that your PR 627 Improve advanced adhesion model is in the Testing Version, what is the situation with this one?

Is it ready to go back into Unstable?

Best wishes,

Chris

**Comment by cesarBLG** [comment]
Hi Chris,
We are not sure about the calculation of steam pressure at the cylinders. Until we figure it out we can't include the changes.

**Comment by cjakeman** [comment]
OK, thanks.
Hope you and Peter can come up with something that's close enough.

**Comment by cesarBLG** [comment]
Closing as Peter is taking over it

**Pull request closed without merging**
