### PR TITLE
Russian Localization Stage III

### PR DESCRIPTION
**Pull request by Weter-ORTS**
The goals are:
- finding sence of unclear strings and translate them;
- ask some programmist(s) to modify GUI spaces for fit russian-translated text on some buttons and fields,
- as well as to make all in-game text strings processable by gettext;
- keep the localization up-to date with the new ORTS features implemented, as soon, as it possible for me;
- trying to translate, if not entry Manual, but at least its Time-table section.

### CODE REVIEW

**Review by YoRyan — APPROVED** [review]
Okay, I've cleaned up this PR so that it merges cleanly into the master and unstable branches. Do you still intend to work on this, @Weter-ORTS, or is it ready to merge as-is?

**Comment by Weter-ORTS** [comment]
Thanks, Ryan for dealing with that not completely clear routine for me.
Then, i'll check the recent source for new changes/additions, then we'llsee.

**Comment by Weter-ORTS** [comment]
I've checked that.
No significant changes detected.
Anyway, here are most recent (26.06 revised) files.
So, let's re-check and proceed.

**Review by YoRyan — APPROVED** [review]
Okay then, this looks good!

**Comment by Weter-ORTS** [comment]
Thank you, Ryan.
the computer's behavior after updating ORTS upset me, but i'll try to work further.

**Comment by Weter-ORTS** [comment]
Hurrah

**Pull request merged**
