### PR TITLE
Adjustment to default connecting rod weights for smaller locomotives

### PR DESCRIPTION
**Pull request by peternewell**
https://bugs.launchpad.net/or/+bug/1895222

### CODE REVIEW

**Review by Sharpe49 — COMMENTED** [review]
Since the weights are used in several places, you should define the values as constants.

**Review by cjakeman — COMMENTED** [review]
Hi Peter,

A small change to the code but I have a few questions, if you don't mind.
 
I didn't realise that there was a problem with the adhesion of smaller locos, so this is news to me but I can see that it might be an issue.
 
The lack of information bothers me. MSTSSteamLocomotive.cs declares values for:
  ReciprocatingWeightLb
  ConnectingRodWeightLb
  ConnectingRodBalanceWeightLb
but doesn't explain where these come from (e.g. a loco that uses these values). Do you know how to find out?
Why a single step at 20 US tons down to 30%?
If this is a linear relationship, would it be sensible to have a factor that reduces down from 100% to 30%?

Just some thoughts,

Chris

**Comment by peternewell** [comment]
> 
> 
> Since the weights are used in several places, you should define the values as constants.

If these parameters are defined as constants, won't that mean that they can't redefine as proposed in this PR?

**Comment by peternewell** [comment]
Inadvertently hit the wrong button.

**Comment by peternewell** [comment]
Hi Chris,

> I didn't realise that there was a problem with the adhesion of smaller locos, so this is news to me but I can see that it might be an issue.
This has come to light with some performance testing of the Rocket locomotive during the "Rainhill" trials. Rocket only weighed 4.25tons(uk), so the current defaults were causing issues with it.

> but doesn't explain where these come from (e.g. a loco that uses these values). Do you know how to find out?
As indicated in the developer notes, the model came from this publication - https://archive.org/details/locomotiveoperat00hend

Refer to Chapter 4 and other supporting sections.

The default values are based upon the values from the example - ie a NYC 4-4-2 locomotive.

Strictly speaking the Rocket, doesn't have the same type of valve gear and connecting rods, so it is probably not a good fit for this model.

> Why a single step at 20 US tons down to 30%?
> If this is a linear relationship, would it be sensible to have a factor that reduces down from 100% to 30%?
I wasn't comfortable that it is a linear relationship. The weight will vary from locomotive to locomotive, and will also change depending upon the length of the rods, and the pivot points of the rods, etc. (see the earlier chapter on valve gear balancing). 

Originally I was contemplating making these parameters user variable, but given the lack of readily available information, I felt that it would just add complexity and confusion for the majority of users. The current defaults seem to work ok for larger locomotives.

As part of my Rocket testing I have also identified some other potential issues that I will be putting bug fixes through for.

Cheers

Petet

**Comment by cjakeman** [comment]
Hi Peter,

> This has come to light with some performance testing of the Rocket locomotive during the "Rainhill" trials. Rocket only weighed 4.25tons(uk), so the current defaults were causing issues with it.

Sounds like a fun project !

 
> As indicated in the developer notes, the model came from this publication - https://archive.org/details/locomotiveoperat00hend
> 
> Refer to Chapter 4 and other supporting sections.
> 
> The default values are based upon the values from the example - ie a NYC 4-4-2 locomotive.

I've looked a bit further in the code and found the reference to "Locomotive Operation - A Technical and Practical Analysis". Now that you've found a URL and the example ("NYC 4-4-2 locomotive"), would you mind adding that info to the comments?


> > Why a single step at 20 US tons down to 30%?
> > If this is a linear relationship, would it be sensible to have a factor that reduces down from 100% to 30%?
> I wasn't comfortable that it is a linear relationship. The weight will vary from locomotive to locomotive, and will also change depending upon the length of the rods, and the pivot points of the rods, etc. (see the earlier chapter on valve gear balancing).
> 
> Originally I was contemplating making these parameters user variable, but given the lack of readily available information, I felt that it would just add complexity and confusion for the majority of users. The current defaults seem to work ok for larger locomotives.

That's absolutely fine - thanks for being patient with me!

It would be nice to see a comment along the lines:
"Simple 2-step adjustment provided as not enough information for a more flexible one."   
so we will know what was in the author's mind.

 
> As part of my Rocket testing I have also identified some other potential issues that I will be putting bug fixes through for.

I'll look out for them.

Thanks,

Chris

**Review by cjakeman — APPROVED** [review]
Hi Peter,

Thanks for adding these comments.

All approved,

Chris

**Comment by cjakeman** [comment]
https://bugs.launchpad.net/or/+bug/1895222

**Pull request merged**
