### PR TITLE
ETCS Driver Machine Interface

### PR DESCRIPTION
**Pull request by cesarBLG**
The display used by the European Train Control System has some areas that cannot be rendered with existing cab controls. This implements the planning area (similar to the Track Monitor) and the text message area.

Now that the master branch includes Monogame, it can be ported back from OR NewYear version.

Discussion: http://www.elvastower.com/forums/index.php?/topic/34577-planning-area-of-the-etcs-dmi/
Blueprint: https://blueprints.launchpad.net/or/+spec/etcs-dmi

### CODE REVIEW

**Comment by Csantucci** [comment]
Hi César,
I tested the unstable release with your PR, using the ETR400. I got this error message:
"Warning: Skipped script j:\microsoft games\train simulator\trains\trainset\b_fs_etr400_pack\script\..\..\common.script\it\tcs_scmtetcs_it_etr400.cs with error:
   'ETCSStatus.ShowTextMessageArea' is obsolete: 'ShowTextMessageArea is deprecated. Use TextMessageAreaShown instead.', line: 794, column: 13"
Note that it is displayed as a Warning, but it prevents the script to be loaded and run. Is it really necessary that you change the naming of ShowTextMessageArea? There are already 800 downloads of the train, and that line is used also in the scripts of other locomotives (e.g. E464). And if you still want to change it, it would be nice if the old naming could still be accepted. By the way, as it is, the message is misleading, because writing "is obsolete" and "is deprecated" usually means that it is still accepted, while in this case it is not accepted.

**Comment by cesarBLG** [comment]
> Hi César,
> Thank you for passing this important feature to the official OR releases!
> I tested the unstable release with your PR, using the ETR400. I got this error message:
> "Warning: Skipped script j:\microsoft games\train simulator\trains\trainset\b_fs_etr400_pack\script....\common.script\it\tcs_scmtetcs_it_etr400.cs with error:
> 'ETCSStatus.ShowTextMessageArea' is obsolete: 'ShowTextMessageArea is deprecated. Use TextMessageAreaShown instead.', line: 794, column: 13"
> Note that it is displayed as a Warning, but it prevents the script to be loaded and run. Is it really necessary that you change the naming of ShowTextMessageArea? There are already 800 downloads of the train, and that line is used also in the scripts of other locomotives (e.g. E464). And if you still want to change it, it would be nice if the old naming could still be accepted. By the way, as it is, the message is misleading, because writing "is obsolete" and "is deprecated" usually means that it is still accepted, while in this case it is not accepted.

My intention was to allow both names, but clearly the compiler doesn't like the deprecation flag, so I'll remove it. I changed the name because having a look at the whole API it seems more consistent, but if there is not an easy way to allow both names, I'll use just the old one, for sure. I have some difficult exams ahead next week, but when I finish with them I'll have a look at this and make sure that the E464 works as in the NewYear release.

**Comment by Csantucci** [comment]
Thanks, César.
Take your time, and fingers crossed for your  exams!

**Comment by cesarBLG** [comment]
@Csantucci I've removed the problematic attribute. Could you please test if the ETR400 is working now?

**Comment by Csantucci** [comment]
@cesarBLG Unfortunately this still doesn't work. I get this message
Warning: Skipped script j:\microsoft games\train simulator\trains\trainset\b_fs_etr400_pack\script\..\..\common.script\it\tcs_scmtetcs_it_etr400.cs with error:
   Property or indexer 'ETCSStatus.ShowTextMessageArea' cannot be assigned to -- it is read only, line: 794, column: 13 .

**Comment by cesarBLG** [comment]
Sorry for that. I'm having trouble starting OR today, so I haven't been able to test it properly. I'm glad it works now.

I've tried to merge this branch into the NewYear version and there are merge conflicts. If you download this branch to your local repository, I think that this command solves the issue (I really hope it works well, because the migration between NewYear and Testing versions has been a nightmare):
git merge -s ours etcs-dmi-display

**Comment by Csantucci** [comment]
Thanks for the effort, César. What did you change passing to the master branch?

**Comment by cesarBLG** [comment]
> Thanks for the effort, César. What did you change passing to the master branch?

Not too much, mainly changed some lines which didn't compile with the Monogame version present in Testing version.

**Comment by YoRyan** [comment]
Pardon me, folks, but where can I download content to test ETCS with?

**Comment by Csantucci** [comment]
Hi Ryan,
I'm sure César will have something for you. From my side the ETR400, that maybe you already downloaded to check the 2D wipers, can be used, together with the equipped route Roma-Napoli V3. Instructions can be found here: http://www.elvastower.com/forums/index.php?/topic/34577-planning-area-of-the-etcs-dmi/page__view__findpost__p__266928 .

**Comment by cesarBLG** [comment]
For testing, I think Carlo's ETCS L2 implementation is the best option. It's both stable and easy to use. Also, the default MSTSTrainControlSystem can be used for quick tests. I can provide another cab with the ETCS DMI installed, if needed.

My ETCS main computer implementation is complex (and full of uncatched bugs). It requires a fitted route (with balises installed next to every signal, and in transition areas), and is implemented as a standalone program, so it's not straightforward to use/install it. However, if you're interested, I can pack it together with instructions.

**Review by YoRyan — APPROVED** [review]
After some changes, I'm approving. Thanks for your patience, Cesar. Merge pending approval by @cjakeman.

**Comment by Csantucci** [comment]
Thank you both for this achievement! I'm really happy that this importante feature is now entering the official OR releases, and that therefore the ETR400 iwll now run flawlessly also under them,

**Comment by cesarBLG** [comment]
Many thanks, Ryan!

**Comment by cjakeman** [comment]
Discussion: http://www.elvastower.com/forums/index.php?/topic/34577-planning-area-of-the-etcs-dmi/
Blueprint: https://blueprints.launchpad.net/or/+spec/etcs-dmi

**Pull request merged**
