### PR TITLE
First phase of https://blueprints.launchpad.net/or/+spec/additional-cruise-control-parameters

### PR DESCRIPTION
**Pull request by Csantucci**
See also http://www.elvastower.com/forums/index.php?/topic/33841-cruise-control/page__view__findpost__p__297586

### CODE REVIEW

**Comment by cesarBLG** [comment]
It looks good to me. I'd add a UseDynBrake here too: https://github.com/openrails/openrails/blob/bae7132c99dbd7821c8c1136a66a6779ed73f57f/Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs#L1403

**Comment by Csantucci** [comment]
> It looks good to me. I'd add a UseDynBrake here too:
> 
> https://github.com/openrails/openrails/blob/bae7132c99dbd7821c8c1136a66a6779ed73f57f/Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs#L1403

OK, done, thanks.

**Comment by cjakeman** [comment]
Hi Carlo,

Wondering why this is still in DRAFT and whether I can approve it.

Thanks,

Chris

**Comment by Csantucci** [comment]
> Hi Carlo,
> 
> Wondering why this is still in DRAFT and whether I can approve it.
> 
> Thanks,
> 
> Chris

Hi Chris,
this was a draft because I had in mind to add further cruise control configuration parameters. This however has not occurred and at the moment I don't foresee actions, so I have just passed the PR to the ready to review state.
Your approval would be welcome.

Thanks for the reminder

Carlo

**Review by cesarBLG — APPROVED** [review]
Hi Carlo, sorry for the delay. I forgot about it.

Changes seem to be useful to cover yet another braking system.

**Comment by Csantucci** [comment]
> Hi Carlo, sorry for the delay. I forgot about it.
> 
> Changes seem to be useful to cover yet another braking system.

Thanks, Cesar. The appveyor doesn' seem to run, and therefore I have the PR stalled.

**Comment by cesarBLG** [comment]
Can you push an empty commit?

The following may also work:
git commit --amend
git push -f

**Comment by Csantucci** [comment]
> Can you push an empty commit?
> 
> The following may also work: git commit --amend git push -f

Thanks Cesar, I pushed a commit with a minor editing correction, then deleted it locally and force pushed the deletion. Now code has remained the same and the AppVeyor has run. Can you please re-review the PR?
Carlo

**Review by cesarBLG — APPROVED** [review]

**Pull request merged**
