### PR TITLE
Fix brakeshoe force bug

### PR DESCRIPTION
**Pull request by peternewell**
Correct issue identified here - 

https://bugs.launchpad.net/or/+bug/2056722

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi Peter,

Why do we have > 21 in the test but "exceeded {20}" in the text? Should they not be the same value, perhaps a named constant? Also should there be a note explaining where this value comes from?

Best wishes,

Chris

**Comment by peternewell** [comment]
> 
> Why do we have > 21 in the test but "exceeded {20}" in the text? Should they not be the same value, perhaps a named constant? Also should there be a note explaining where this value comes from?
> 

Point taken, I have now changed it all to 20. Thanks for pointing this out.

**Review by cjakeman — APPROVED** [review]
Hi Peter,

Thanks for this change.

Approved,

Chris

**Comment by peternewell** [comment]
Thanks Chris

**Pull request merged**
