### PR TITLE
Trim whitespace from timetable-or cells

### PR DESCRIPTION
**Pull request by cjakeman**
Remove leading and trailing whitespace which is difficult to see in a spreadsheet and may confuse the timetable author.

See Timetable parser allows confusing spaces at https://bugs.launchpad.net/or/+bug/1900308

### CODE REVIEW

**Comment by YoRyan** [comment]
I'm a little confused. We don't write back to the timetable file, so where would the extraneous whitespace come into play? The list of trains in the launcher? The dispatch window? References between trains?

**Comment by YoRyan** [comment]
Regardless, I suggest shortening the new function to
```diff
diff --git a/Source/Orts.Parsers.OR/TimetableReader.cs b/Source/Orts.Parsers.OR/TimetableReader.cs
index 685af405f..04a6f2511 100644
--- a/Source/Orts.Parsers.OR/TimetableReader.cs
+++ b/Source/Orts.Parsers.OR/TimetableReader.cs
@@ -52,24 +52,12 @@ public TimetableReader(string filePath)
                 // extract and store all strings
                 do
                 {
-                    Strings.Add(TrimElements(readLine, separator));
+                    Strings.Add((from s in readLine.Split(separator[0])
+                                 select s.Trim())
+                                 .ToArray());
                     readLine = filestream.ReadLine();
                 } while (readLine != null);
             }
         }
-
-        /// <summary>
-        /// Remove leading and trailing whitespace which is difficult to see in a spreadsheet and may confuse the timetable author.
-        /// </summary>
-        /// <param name="readLine"></param>
-        /// <param name="separator"></param>
-        /// <returns></returns>
-        private string[] TrimElements(string readLine, string separator)
-        {
-            var lineElements = readLine.Split(separator[0]);
-            for (var i = 0; i < lineElements.Count(); i++)
-                lineElements[i] = lineElements[i].Trim();
-            return lineElements;
-        }
     }
 }

```
What do you think, Chris?

**Comment by cjakeman** [comment]
Hi Ryan,

> I'm a little confused.

Sorry to be confusing. I've re-written the comments and hope that will be clearer.

When a timetable author uses a spreadsheet to prepare a timetable and includes a spurious space then the timetable fails to match text from one cell with text from another but the reason is very difficult to find.

It's a problem that has caused some pain.

Chris

**Comment by cjakeman** [comment]
Hi Ryan,

> Regardless, I suggest shortening the new function to
> 
> What do you think, Chris?

A good idea. Implemented and tested.

Best wishes,

Chris

**Review by YoRyan — APPROVED** [review]
This looks ready to go now. Cheers, Chris!

**Pull request merged**
