### PR TITLE
Announce train driving window

### PR DESCRIPTION
**Pull request by cjakeman**
Small change to extend the new features item to include in-game Train Dr

"cjakeman wants to merge 3 commits into openrails:master from cjakeman:announce-train-driving-windowiving window in the manual and on the website page." NO. I started from release/1.4, not master. and I want to merge into release/1.4 I don't have the option to change from master :-(

### CODE REVIEW

**Comment by Sharpe49** [comment]
Hi,
You have the manual update about Software platorm in this commit.

**Comment by twpol** [comment]
> You have the manual update about Software platorm in this commit.

Looks like that is fixed by changing the target to the 1.4 branch

**Comment by twpol** [comment]
> "cjakeman wants to merge 3 commits into openrails:master from cjakeman:announce-train-driving-windowiving window in the manual and on the website page." NO. I started from release/1.4, not master. and I want to merge into release/1.4 I don't have the option to change from master :-(

Hmm, that's weird, you should have been able to set it via this dropdown:

image

I've changed it for you now

**Comment by cjakeman** [comment]
> I've changed it for you now

Thanks, James

**Comment by YoRyan** [comment]
Ported to Jekyll with https://github.com/YoRyan/openrails.org/commit/c5e1e18ffd2777f595e142a7a8ca00c13d83d0b8.

**Pull request merged**
