### PR TITLE
feat: Clean up Sphinx build and configuration

### PR DESCRIPTION
**Pull request by twpol**
The Testing Version failed to build today, so I had a look at the whole manual build and found that it's from a 2015 template. I have replaced it with the latest Sphinx quickstart template, which hugely simplifies the `make.bat` code - which should fix the build problem and might reduce the dependencies needed to build documentation locally.

I also took the opportunity to put the correct version number into the manual.

### CODE REVIEW

**Comment by YoRyan** [comment]
Not working for me, getting:
```
Running Sphinx v3.2.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\ra_yo\Documents\Projects\openrails-manual\WPy32-3850\python-3.8.5\lib\site-packages\sphinx\config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\ra_yo\Documents\Projects\openrails-manual\WPy32-3850\python-3.8.5\lib\site-packages\sphinx\util\pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "C:\Users\ra_yo\Documents\Projects\openrails\Source\Documentation\Manual\conf.py", line 29, in <module>
    exec(open("./version.py").read())
FileNotFoundError: [Errno 2] No such file or directory: './version.py'
```
when I run `make html` or `make latexpdf`. Any advice?

**Review by cjakeman — APPROVED** [review]
Hi James,

Looks a lot simpler and with better notes.

Approved with thanks,

Chris

**Comment by twpol** [comment]
> Not working for me, getting:
> when I run `make html` or `make latexpdf`. Any advice?

Did you run `Build.cmd` first? That generates the version file.

**Comment by YoRyan** [comment]
I didn't want to set up an entire build environment, so I created a `version.py` file with:
```
version = 'X'
revision = '000'
```
which did the trick.

**Comment by twpol** [comment]
@YoRyan I've hopefully removed the need to create `version.py` (or do any other messing about) in #281

**Pull request merged**
