### PR TITLE
Animated wipers for 2D cabs

### PR DESCRIPTION
**Pull request by Csantucci**
Feature request: https://www.elvastower.com/forums/index.php?/topic/34604-2d-cabs-wipers-animation/

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi Carlo,

Does this addition require any changes to the Manual?

Best wishes,

Chris

**Comment by YoRyan** [comment]
Yes, I believe so, Chris. This PR adds new properties to the .cvf file.

**Comment by Csantucci** [comment]
Yes, it's so; sorry for not having mentioned that. I'll prepare the addition to the manual as soon as the code is considered OK. By the way, Ryan, I assume you are in the middle of code changes, because the moving wipers don't appear when running the latest Unstable release.

**Comment by YoRyan** [comment]
> By the way, Ryan, I assume you are in the middle of code changes, because the moving wipers don't appear when running the latest Unstable release.

Oh, shoot! No, that wasn't intentional. Is it possible you could PM or email me a content sample to test with?

**Comment by Csantucci** [comment]
@Ryan , you may download here http://www.trainsimhobby.net/infusions/pro_download_panel/download.php?did=1980 a HST that has animated 2D wipers. You might check the Disable TCS option.

**Comment by YoRyan** [comment]
Thanks for the link, Carlo!

As it turns out, the changes we made to CabViewFile.cs conflicted with some changes made to the same file by #384, so the code bot was excluding this PR from the unstable release. I have rearranged the additional line so that the auto merge will work.

By my testing, the wipers are working.

**Comment by Csantucci** [comment]
Yes, it works now. I should have noticed by myself that the PR was no more present in the unstable release, sorry.

**Comment by YoRyan** [comment]
To be clear, Carlo, this code looks good, and you may proceed with updating the manual.

**Comment by Csantucci** [comment]
Ryan, thanks for green light. OR manual updated.

**Review by YoRyan — APPROVED** [review]
Merge pending approval by @cjakeman.

**Review by cjakeman — APPROVED** [review]
Hi Carlo,

All looks good.

Approved with thanks,

Chris

**Pull request merged**
