### PR TITLE
Further strings translation

### PR DESCRIPTION
**Pull request by Weter-ORTS**

### CODE REVIEW

**Review by Weter-ORTS — COMMENTED** [review]
have just removed that two ocassionally saved files:
i only closed PoEdit with "save" button instead of cross
i.e. no actual modifications, but new date of modification

**Comment by Sharpe49** [comment]
You deleted the files instead of remove them from the commit.
You can go back to the first commit using the git reset function.
Then amend the commit in order to remove the files from the commit.
Then force push the new commit to Github.

**Comment by Weter-ORTS** [comment]
> removing them from the commit.
how to do that correct?

**Comment by Sharpe49** [comment]
Which software are you using for Git?

**Comment by Weter-ORTS** [comment]
firefox browser only

**Comment by Weter-ORTS** [comment]
> You can go back to the first commit using the git reset function.
> Then amend the commit in order to remove the files from the commit.
new words for me, sorry

**Comment by Sharpe49** [comment]
So the Github website directly? OK, you will need a Windows application to do this change. You can use TortoiseGit (but it is a bit complicated) or SourceTree (which is simpler).

**Comment by Weter-ORTS** [comment]
Ryan did show to me fetch button:
as i understood, this updates all material with newer dates from master branch,
after removing that two ones, i fetched my branch
I expect, that missing files will be restored

**Comment by Sharpe49** [comment]
No, this won't work here.

**Comment by Weter-ORTS** [comment]
so what must i do?

**Comment by Sharpe49** [comment]
As I said, you need to download a Windows Git application as the ones mentioned before.

**Comment by Weter-ORTS** [comment]
but what if closing that PR and starting new one with only three "right" files?

**Comment by Weter-ORTS** [comment]
TBH i, being no programmist would prefer a simplest way, that worked all last year.

**Comment by Sharpe49** [comment]
> but what if closing that PR and starting new one with only three "right" files?

This could work.

**Comment by Weter-ORTS** [comment]
so, new PR...

**Comment by Weter-ORTS** [comment]
restarting...

**Pull request closed without merging**
