### PR TITLE
Distributed Power Air Brake Synchronization

### PR DESCRIPTION
**Pull request by SteelFill**
This PR adds a sorely missing feature for distributed power: the ability for remote locomotives to apply and release train/loco brakes in response to what the player locomotive is doing. This can dramatically improve brake response times on very long trains, the American creators out there will no doubt appreciate this.

[Relevant roadmap card](https://trello.com/c/urWcGqkA)
[Discussion thread on Elvas Tower](https://www.elvastower.com/forums/index.php?/topic/26249-remote-control-dpu-units/page__view__findpost__p__305271)

Changes:
- Changes to air brake propagation code to allow locomotives other than the player locomotive to apply/release brakes.
- Complete rewrite of engine brake code to allow groups of locomotives other than the player group to apply/release engine brakes. Also added a fix that allows steam locomotives to bail off the locomotive brake application on their tender.
- New token `engine(ORTSDPBrakeSynchronization` to allow users to decide which brake behavior should be transmitted from the lead locomotive to remote locomotives. `ORTSDPBrakeSynchronization ( "Apply, Release, Emergency, Independent" )` will fully enable brake synchronization. `"Apply"` means the remotes can apply the train brake, `"Release"` means remotes can release the train brakes, `"Emergency"` for remote emergency brake applications, and `"Independent"` allows remote units to change the locomotive brake to match the lead unit's brake cylinder pressure (including bail-off). Any combination of settings can be used. If the `ORTSDPBrakeSynchronization` token is missing, then the only setting active will be `"Independent"` since this somewhat replicates the default behavior from previous versions. Note that a setting will only have effect if BOTH the player locomotive and the distributed power locomotive have that setting.
- New cab view control `ORTS_TRAIN_AIR_FLOW_METER` which behaves like `ORTS_AIR_FLOW_METER` but will show the air flow rate for all locomotives in the train, rather than just the player locomotive. This distinction only matters if the train has distributed power units that can release the train brakes.
- Changed F5 HUD to show the total flow rate of all locomotives instead of just the player locomotive flow rate.
- Small rewrite to compressor activation logic to allow compressors to synchronize in groups of locomotives other than the lead locomotive. Also improved accuracy of compressor synchronization; if one locomotive still needs air, connected locomotives will be allowed to overcharge their MR by up to 5 psi in order to provide the demanded air.
- Bail-off will now use the engine brake release speed instead of the train brake release speed, should make bail-off take a lot less time.

In addition to testing how DPUs work with air brakes, it's also worth checking completely unmodified and legacy content as the rewrite of so much air brake code could do almost anything.

### CODE REVIEW

**Comment by SteelFill** [comment]
I only realized now that a conflict with my other PR #912 has prevented this PR from being added to Unstable for around a week. Resolving that might have to wait for one of the two PR's to be merged. I think this PR will be best to merge first as there are only a couple of small things I want to investigate.

**Comment by SteelFill** [comment]
@Csantucci Carlo, I have reached a good stopping point with this PR and I'd appreciate it if you could do the review since I believe you have the most exposure to the DPU code.

**Comment by Csantucci** [comment]
> @Csantucci Carlo, I have reached a good stopping point with this PR and I'd appreciate it if you could do the review since I believe you have the most exposure to the DPU code.

Hi,
unfortunately I don't have a good knowledge about brakes. I can give a first approval, after having checked that the existing part of DPU management still works correctly , but I'd suggest you to ask also César for a further review. He has already reviewed brake related PRs.

**Comment by SteelFill** [comment]
> > @Csantucci Carlo, I have reached a good stopping point with this PR and I'd appreciate it if you could do the review since I believe you have the most exposure to the DPU code.
> 
> Hi, unfortunately I don't have a good knowledge about brakes. I can give a first approval, but I'd suggest you to ask also César for a further review. He has already reviewed brake related PRs.

Understandable, I'll also ping Cesar.

**Comment by SteelFill** [comment]
@cesarBLG Hey Cesar, this PR includes quite a few air brake changes, including some interactions with your work. It would help to have your review.

**Comment by SteelFill** [comment]
> Is it wanted that the fence has no influence in the braking behaviour?

Yep, while there are some DPU modes that change brake behavior, the fence has no effect. For normal driving, you always want every controlling locomotive to use the same level of brake application.

**Comment by Csantucci** [comment]
> > Is it wanted that the fence has no influence in the braking behaviour?
> 
> Yep, while there are some DPU modes that change brake behavior, the fence has no effect. For normal driving, you always want every controlling locomotive to use the same level of brake application.

OK, to me the PR is OK. Let's wait César's comments. I wonder if you could for some days remove from unstable your triplevalve PR; this way the present PR should compile without errors in the unstable release, and you could have some feedback from users.

**Review by cesarBLG — COMMENTED** [review]
It looks OK for me too. I agree with Carlo that we should keep it in Unstable for a while, to detect potential mistakes in some of the formulas, which can be messed up easily.

Note that 'for-unstable' is the default behaviour for OR development team, and you have to explicitly use 'not-for-unstable' to prevent a PR from entering it.

**Review by cesarBLG — APPROVED** [review]
It looks OK to me, thanks. No bugs have been reported during this week, so I'll approve.

**Pull request merged**
