### PR TITLE
Generic items: optional internal 3DCab animation linked to them

### PR DESCRIPTION
**Pull request by Csantucci**
This  is an extension of https://blueprints.launchpad.net/or/+spec/cabview-controls-for-generic-items .
See http://www.elvastower.com/forums/index.php?/topic/35572-cabview-controls-for-generic-items/page__view__findpost__p__279164

### CODE REVIEW

**Review by pzgulyas — APPROVED** [review]
Obvious change.

**Comment by Csantucci** [comment]
> Obvious change.

Thanks Peter! Sorry to bother you, but I didn't update the manual. I've done it now. So I kindly ask you to approve the PR again.

**Review by pzgulyas — APPROVED** [review]
No problem at all!

**Comment by Csantucci** [comment]
> No problem at all!

Very kind as always!

**Pull request merged**
