### PR TITLE
Upgraded to MonoGame 3.8.0 (+ small update for other libraries)

### PR DESCRIPTION
**Pull request by Sharpe49**
NB : Switching to MonoGame 3.8.0 has an impact on effects compilation (which is currently done at runtime).
It can no longer be executed from the MonoGame.Framework.Content.Pipeline assembly because it needs to have mgfxc installed as a dotnet tool locally and the tool can't be added to the Program folder since it's dependencies are compiled for .Net Core.

Effects compilation is now done during Open Rails build. That's why effects files in the Program\Content folder are now .mgfx files after build.

And we can't update to MonoGame 3.8.1 because it is .Net 6 only.

Feature request: Missing (please add Elvas Tower, Trello, Launchpad link if one exists)

### CODE REVIEW

**Comment by cesarBLG** [comment]
The CI builds are failing, and the log reports a failure in effects compilation

**Comment by Sharpe49** [comment]
AppVeyor does report a success just above. Where do you see this failure ?

**Comment by cesarBLG** [comment]
It's from the bot that generates the Unstable builds: https://james-ross.co.uk/projects/or/ci_log.txt
The log can be accessed from the main page of the repository (it shows Builds | Failing)

**Comment by Sharpe49** [comment]
Ok, James is using Jenkins and its config file is not in the repository. I will move the dotnet tool restore command from the AppVeyor CI file to the Build.cmd file.

**Comment by Sharpe49** [comment]
Or better, to the PostBuildActions.bat file

**Comment by Sharpe49** [comment]
Ok, waiting for a new Jenkins build.

**Comment by Sharpe49** [comment]
Yep, it worked.

**Comment by Sharpe49** [comment]
There was some issues because, after rebase, some wrong references were still there. I pushed a new version that fixes this issue.

**Comment by cjakeman** [comment]
Hi Cedric,

I've added the not-for-unstable label again as this PR was again passing through the Appveyor, but the build was failing with:

C:\Jenkins\jobs\Open Rails Unstable\workspace\Source\Orts.Parsers.OR\Orts.Parsers.OR.csproj(21,5): error MSB4025: The project file could not be loaded. The 'PackageReference' start tag on line 17 position 6 does not match the end tag of 'ItemGroup'. Line 21, position 5.

This may be something to do with the git operation that merges *.csproj files as James mentioned that it uses merge=union.  I will ask him to change it so that the XML tags in *.csproj are not so easily broken.

Best wishes,
Chris

**Comment by cjakeman** [comment]
Now that another PR which conflicted has been merged, I removed label not-for-unstable to see if the XML tags in this project file would survive the merge. It didn't - see below, so I have restored the label: 

C:\projects\openrails\Source\Orts.Parsers.OR\Orts.Parsers.OR.csproj(28,5): error MSB4025: The project file could not be loaded. The 'PackageReference' start tag on line 22 position 6 does not match the end tag of 'ItemGroup'. Line 28, position 5.

**Review by cjakeman — APPROVED** [review]
Hi Cedric,

I've removed the not-for-unstable label and see it's all working now.

Thanks for changing the .gitattributes

Chris

**Pull request merged**
