### PR TITLE
Correct double heading bug

### PR DESCRIPTION
**Pull request by peternewell**
Fix for this bug - https://bugs.launchpad.net/or/+bug/1984049

Enhancements are cover by this blueprint - https://blueprints.launchpad.net/or/+spec/diesel-performance
Additional enhancements will be added in a further PR later.

Some of the enhancements added are described in this thread - 
http://www.elvastower.com/forums/index.php?/topic/35993-diesel-mechanical-locomotive/

### CODE REVIEW

**Comment by Csantucci** [comment]
Hi Peter, is there a blueprint or a Trello box that cover the Enhancement aspects of this PR?

**Comment by peternewell** [comment]
> Hi Peter, is there a blueprint or a Trello box that cover the Enhancement aspects of this PR?

Hi Carlo, I have modified the description for this PR to include the information that you are seeking.

**Review by Csantucci — APPROVED** [review]
It's OK to me, thanks for the improvements!

**Comment by peternewell** [comment]
Hi Carlo,

Thanks for that.

**Pull request merged**
