### PR TITLE
New strings at Steamer's HUD translated Russian

### PR DESCRIPTION
**Pull request by Weter-ORTS**
Thanks to @peternewell for his knowledge and website
Also, few corrections to Menu and Common sections commited

### CODE REVIEW

**Comment by YoRyan** [comment]
Hi Weter,

Thanks again, and just let us know when this is ready to go.

**Comment by cjakeman** [comment]
Hi Weter,

> Thanks again, and just let us know when this is ready to go.

I've added the label "For Unstable" so your work will appear in the Unstable version.

As Ryan said a while back, please let us know when you are ready for us to publish this to the Testing version.

Thanks,

Chris

**Comment by Weter-ORTS** [comment]
> > Thanks again, and just let us know when this is ready to go.

@Chris
I say my "OKay" to You

**Comment by Csantucci** [comment]
Approved, thank you for contribution

**Review by Csantucci — APPROVED** [review]

**Pull request merged**
