### PR TITLE
Add water mass to diesel locomotive mass

### PR DESCRIPTION
**Pull request by peternewell**
Correct issues with water mass not added to diesel locomotives for steam heating. - https://bugs.launchpad.net/or/+bug/1899459

### CODE REVIEW

**Comment by YoRyan** [comment]
Hi Peter,

The diesel locomotive mass fix looks good, but could you explain the changes you've made to the steam heating code in this PR?

Specifically, you've deleted lines like these:

```
float FuelOilConvertLtoKg = 0.85f;
MassKG -= FuelUsageLpS * elapsedClockSeconds * FuelOilConvertLtoKg;
```

**Comment by peternewell** [comment]
This removes a duplication in adjusting the mass of the car due to diesel fuel usage. The usage is accounted for in another section of code.

**Comment by YoRyan** [comment]
So were we actually double-counting the water usage of steam heaters?

**Comment by peternewell** [comment]
> So were we actually double-counting the water usage of steam heaters?
Yes, correct.

**Review by YoRyan — APPROVED** [review]
Okay, thanks for the clarification. Approved.

**Pull request merged**
