### PR TITLE
It locales 1.4

### PR DESCRIPTION
**Pull request by strawberryfield**
IT locales update

### CODE REVIEW

**Review by YoRyan — APPROVED** [review]
Looks good! Thanks very much.

**Comment by Sharpe49** [comment]
@strawberryfield @YoRyan You were too quick with this pull request: it includes modifications with the POT files that are just date modifications. These should not be included in your commits.

**Comment by cjakeman** [comment]
@YoRyan Can you explain to me how to fix this and I try to do so?

Thanks,

Chris

**Comment by YoRyan** [comment]
> @strawberryfield @YoRyan You were too quick with this pull request: it includes modifications with the POT files that are just date modifications. These should not be included in your commits because they can cause merge conflicts with other pull requests that are actually modifying these templates to add new translations.

Terribly sorry—I wasn't aware of this policy. With #419, I have selectively reverted the files that only had timestamp bumps.

**Pull request merged**
