### PR TITLE
Bug fix for https://bugs.launchpad.net/or/+bug/1910746. By Buttercup.

### PR DESCRIPTION
**Pull request by mbm-OR**
Timetable, /closeup qualifier not working with $triggers dispose command.

### CODE REVIEW

**Comment by Csantucci** [comment]
Let's wait that Buttercup tests this in the Unstable release, and when the test is OK,  the PR can be approved.

**Comment by Csantucci** [comment]
Mauricio,
did you have feedbacks from Buttercup?

**Comment by mbm-OR** [comment]
I got an OK, from Buttercup, for the OR-NewYear-MG version.

**Comment by Csantucci** [comment]
OK, that's enough to approve this.

**Review by Csantucci — APPROVED** [review]

**Comment by YoRyan** [comment]
Since this has spent a week in unstable, I think it's also ready to merge.

**Pull request merged**
