### PR TITLE
Correct a timing issue in Eames brakes

### PR DESCRIPTION
**Pull request by peternewell**
https://bugs.launchpad.net/or/+bug/1956265

### CODE REVIEW

**Review by Csantucci — COMMENTED** [review]
Maybe the S at the end of AdjBrakeServiceTimeFactorS is misleading and could be replaced by PSIpS?

**Comment by peternewell** [comment]
> Maybe the S at the end of AdjBrakeServiceTimeFactorS is misleading and could be replaced by PSIpS?

I have made the changes that you suggested. 

For consistencey I needed to make the changes in other classes as well.

Are you able to approve?

**Review by Csantucci — APPROVED** [review]
That's OK now, thank you.

**Comment by peternewell** [comment]
Thanks for that.

**Pull request merged**
