### PR TITLE
feat: Remove unnecessary Windows.Forms usage

### PR DESCRIPTION
**Pull request by twpol**
Roadmap: https://trello.com/c/TrIB2nUc/533-cross-platform-portability-support-for-linux-macos

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi James,

I searched for "Path.GetDirectoryName(Application.ExecutablePath)" and found 2 occurences - in Launcher\Program.cs and TrackViewer\UserInterface\Languages.cs

Would these be better as "ApplicationInfo.ProcessDirectory" instead?

! searched for "VersionInfo.FileDescription" and found 1 occurance - in ORTS.Updater\UpdateManager.cs.

Would this be better as "ApplicationInfo.ApplicationName" instead?

All the rest looks good.

Chris

**Comment by twpol** [comment]
> I searched for "Path.GetDirectoryName(Application.ExecutablePath)" and found 2 occurences - in Launcher\Program.cs and TrackViewer\UserInterface\Languages.cs

For `Launcher`, we can't because `ApplicationInfo` is in `ORTS.Common` which unfortunately loads RailDriver and MonoGame; a better reorganisation of the libraries could enable this one to be changed, though

For `TrackViewer`, I ignored the contributed projects which I am not familiar enough with to test; they can be updated by their own authors

> ! searched for "VersionInfo.FileDescription" and found 1 occurance - in ORTS.Updater\UpdateManager.cs.

For `ORTS.Updater`, this particular code is scanning the newly downloaded executables, so it should not be changed (`pathName` is set to `PathUpdateStage` which is the `UpdateStage` subdirectory we extract updates to)

**Comment by cjakeman** [comment]
Marking this as not-for-unstable so that it no longer conflicts with PR980.
This is temporary - just for this weekend.

**Review by cjakeman — APPROVED** [review]
Hi James,

Thanks for responding to my comments.

Approved and merged.

Chris

**Pull request merged**
