### PR TITLE
Russification/weter

### PR DESCRIPTION
**Pull request by Weter-ORTS**
Revision of 2 *.po-files, adding new or correcting existing translations

### CODE REVIEW

**Comment by Weter-ORTS** [comment]
Is there more effective way how to know some strings meanings (wiewing _*.po_-file shows module name and number of string among code), so where else, than ET forum can I ask coders for explanation?

**Comment by YoRyan** [comment]
If you can read the C# code, that would be the quickest way. Update your .po file with gettext and then look up the context of each string by its .cs filename and line number.

**Comment by Weter-ORTS** [comment]
> 
> 
> If you can read the C# code, that would be the quickest way. Update your .po file with gettext and then look up the context of each string by its .cs filename and line number.

Sorry, but C# is not my strong side yet(

**Comment by Sharpe49** [comment]
Every changes from this pull request are included in pull request #248.
Shall I close this PR?

**Comment by Weter-ORTS** [comment]
> 
> 
> Every changes from this pull request are included in pull request #248.
> Shall I close this PR?

Yes, please.
I've compared edits, added to*.po-files manually with ones, made last two days at POEdit.
All of them are at #248 now.
Have a nice day.

**Comment by YoRyan** [comment]
Very well. Note that you have the ability to close your own PR's.

**Pull request closed without merging**
