### PR TITLE
Correct issue with mechanical compressors not showing in HuD

### PR DESCRIPTION
**Pull request by peternewell**
https://blueprints.launchpad.net/or/+spec/brake-enhancements

This corrects an issue identified in this thread -

Bug report: https://www.elvastower.com/forums/index.php?/topic/35526-possible-air-brake-compressor-bug-in-monogame-v105/

### CODE REVIEW

**Comment by Sharpe49** [comment]
You know, you just had to click on the branch name (openrails:master), just below the title of the pull request, to change the branch.

**Review by Sharpe49 — APPROVED** [review]

**Comment by peternewell** [comment]
> 
> 
> You know, you just had to click on the Edit button to change the branch.

Thanks for that and the approval.

However it appears that I built it on the base of unstable version, rather then rc1.4. So James asked me to rebuild it on that base instead.

**Comment by twpol** [comment]
> You know, you just had to click on the Edit button to change the branch.

Unfortunately, not always

If the pull request was not based on `release/1.4` initially, it may pull in unexpected and unwanted changes from `master` (or whatever other branch was used)

And beyond that, even if a specific case might have worked, it is better for everyone to learn the basic steps necessary to contribute to this new release process so that future releases are much smoother and safer :)

**Review by twpol — APPROVED** [review]
Thanks for this fix Peter!

**Pull request merged**
