### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Weter-ORTS**
Translated almost all, that I knew.

### CODE REVIEW

**Comment by Weter-ORTS** [comment]
I have found the ":" symbol inside meaning string at RunActivity.po ("Dispetcher Info **:** active trains **:**")
Maybe, this leads to error, as I see, that ":" is used as command prefix at code-strings?

**Comment by YoRyan** [comment]
Thank you again for your translations. Is this ready yet to be merged?

**Comment by YoRyan** [comment]
Thank you very much for your translations. If you have finished your work, I am ready to review it.

> I have found the ":" symbol inside a meaning string at RunActivity.po ("Dispatcher Info **:** active trains **:**")
> Line 1343
> Maybe, this leads to an error, as soon as I see, that ":" is used as command-prefix at code-strings?

It looks like this string is [for rendering a header on the GUI](https://github.com/openrails/openrails/blob/4d61887252746f5adc2714d9f7950d7a4fe8a097/Source/RunActivity/Viewer3D/Popups/HUDWindow.cs#L916), not multiplayer command processing, so I don't think this should be a problem.

**Comment by Weter-ORTS** [comment]
> Thank you very much for your translations. If you have finished your work, I am ready to review it.
Thank You in turn. I Think, there's enough of work was done to try.

> > Maybe, this leads to an error, as soon as I see, that ":" is used as command-prefix at code-strings?
> 
> It looks like this string is [for rendering a header on the GUI](https://github.com/openrails/openrails/blob/4d61887252746f5adc2714d9f7950d7a4fe8a097/Source/RunActivity/Viewer3D/Popups/HUDWindow.cs#L916), not processing multiplayer commands, so I don't think this should be a problem.

I've mentioned, that thIs string is STILL rendered in English, even after it was translated, so i thought, that ":" was the reason.

**Comment by YoRyan** [comment]
Oh, I see. The reason is because that code is passing the string to the translation system with the number of active trains already inserted. So it should be changed from

```
TextPageHeading(table, Viewer.Catalog.GetString("DISPATCHER INFORMATION : active trains : " + totalactive));
```

to

```
TextPageHeading(table, f$"{Viewer.Catalog.GetString("DISPATCHER INFORMATION : active trains")} : {totalactive}");
```

And then you should be able to translate `"DISPATCHER INFORMATION : active trains` and have the Russian version appear in the simulator.

If you don't feel comfortable making this change, I can do it myself, but it will have to be in another PR.

**Comment by Weter-ORTS** [comment]
> If you don't feel comfortable making this change, I can do it myself, but it will have to be in another PR.
To be honest, I didn't learn C#usage yet, as I'm not a coder, so do, please.
So What about review? ;)

**Comment by Weter-ORTS** [comment]
@YoRyan
First, thank for review.
Second: "new warning messages" was it for me?
Please, look at Simulation or RunActivity for brake system tokens(EQ,BP,BC), which are not appear as a strings in *.pot-files, so I can't translate them.
They are appear at the center of HUD and are very important, as they show status of train brakes, so they need to be translated to  УР,ТМ,ТЦ

**Comment by Weter-ORTS** [comment]
@YoRyan
First, thank for review.
Second: "new warning messages" was it for me?
Please, look at Simulation or RunActivity for brake system tokens(EQ,BP,BC), which are not appear as a strings in *.pot-files, so I can't translate them.
They are appear at the center of HUD and are very important, as they show status of train brakes, so they need to be translated to  УР,ТМ,ТЦ

**Comment by Weter-ORTS** [comment]
@YoRyan
First, thank for review.
Second: "new warning messages" was it for me?
Please, look at Simulation or RunActivity for brake system tokens(EQ,BP,BC), which are not appear as a strings in *.pot-files, so I can't translate them.
They are appear at the center of HUD and are very important, as they show status of train brakes, so they need to be translated to  УР,ТМ,ТЦ

**Comment by Weter-ORTS** [comment]
@YoRyan
First, thank for review.
Second: "new warning messages" was it for me?
Please, look at Simulation or RunActivity for brake system tokens(EQ,BP,BC), which are not appear as a strings in *.pot-files, so I can't translate them.
They are appear at the center of HUD and are very important, as they show status of train brakes, so they need to be translated to  УР,ТМ,ТЦ

**Comment by Weter-ORTS** [comment]
@YoRyan
First, thank for review.
Second: "new warning messages" was it for me?
Please, look at Simulation or RunActivity for brake system tokens(EQ,BP,BC), which are not appear as a strings in *.pot-files, so I can't translate them.
They are appear at the center of HUD and are very important, as they show status of train brakes, so they need to be translated to  УР,ТМ,ТЦ

**Comment by YoRyan** [comment]
Okay, I'll take a look soon. I'll need to file a PR to make those strings translatable, and then you can submit a new translation.

**Comment by Weter-ORTS** [comment]
@YoRyan Hi!
So, I have to start new PR in order to work further, right?

**Comment by YoRyan** [comment]
Yes, but wait for my PR first. I will notify you when I've filed it.

**Comment by YoRyan** [comment]
@Weter-ORTS, it appears those strings are already present in Source\Locales\RunActivity\RunActivity.pot.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by Weter-ORTS** [comment]
@YoRyan Thank You.
1. tell me, please, if I've created my own branch(the PR confirmed by You was taken from it), is it compulsory to make a new branch to work further, since that PR was merged, or the old branch's content will automatcally be updated?
2. I found some another problems with translation process, which need to be discussed with programmist. So, may I invite You to ET's translation thread to speak about it more verboose?
After most of strings was translated, it's good time. I suppose, to think about that problems and work with them at the next stage of localization.

**Comment by YoRyan** [comment]
1. It's not compulsory. Some people prefer to create new branches for every new feature or bug fix they're working on, but it makes Git more difficult to use. If you stick with your master branch, use `git pull https://github.com/openrails/openrails.git master` to merge in the changes from upstream, and then use `git push origin master` to sync up your own GitHub fork. Then when you create your next PR, you should have a clean patch.
2. Sure thing. I've subscribed to your [thread](http://www.elvastower.com/forums/index.php?/topic/26556-translations-unclear-strings-other-problems/) on ET and will answer any questions you have on there.

**Comment by Weter-ORTS** [comment]
@YoRyan Hello.
Thanks for suscribing and answering.
How should I use that two commands exactly? where to type them?

**Comment by Weter-ORTS** [comment]
@YoRyan Hello.
Thanks for suscribing and answering.
How should I use that two commands exactly? where to type them?

**Comment by YoRyan** [comment]
Oh, those are terminal commands you run in a checked-out repository on your machine. I forgot you were using the web interface to upload your files.

In that case, I believe the easiest way to sync back up would be to delete your openrails fork and then create a new one.

**Comment by Weter-ORTS** [comment]
And, how to delete it?
I can create a new fork first?

**Comment by Weter-ORTS** [comment]
And, how to delete it?

**Comment by YoRyan** [comment]
See [GitHub's help page](https://help.github.com/articles/deleting-a-repository).

**Comment by Weter-ORTS** [comment]
@YoRyan thanks!
So, goodbye, Yellow-brick road...

**Comment by Weter-ORTS** [comment]
> @Weter-ORTS, it appears those strings are already present in Source\Locales\RunActivity\RunActivity.pot.
Yes, It's allright now-I checked.

**Pull request merged**
