### PR TITLE
Fix 3D cab digit and gauge stuttering on Monogame (round 3)

### PR DESCRIPTION
**Pull request by YoRyan**
Targeting the master branch this time.

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi Ryan,

 

Thanks for trying yet again.

 

I’ve added the label “for-unstable” so it gets added to the unstable branch.

 

2 things:

 

1.      Don’t delete your branch  <https://github.com/YoRyan/openrails/tree/mg-cab-stutter3> YoRyan:mg-cab-stutter3 just yet. It needs to stay available until the PR has been included into the master branch.

2.      The AppVeyor build failed.

 

"C:\projects\openrails\Source\ORTS.sln" (Clean;Build target) (1) ->

"C:\projects\openrails\Source\RunActivity\RunActivity.csproj" (default target) (9:6) ->

(CoreCompile target) -> 

Viewer3D\Shapes.cs(1292,13): error CS0103: The name 'DummyVertexBuffer' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1292,66): error CS0103: The name 'DummyVertexDeclaration' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1293,13): error CS0103: The name 'DummyVertexBuffer' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1293,39): error CS0103: The name 'DummyVertexData' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1294,13): error CS0103: The name 'VertexBufferBindings' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1294,48): error CS0246: The type or namespace name 'VertexBufferBinding' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1294,87): error CS0246: The type or namespace name 'VertexBufferBinding' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

Viewer3D\Shapes.cs(1294,107): error CS0103: The name 'DummyVertexBuffer' does not exist in the current context [C:\projects\openrails\Source\RunActivity\RunActivity.csproj]

 

Do you know what’s wrong?

 

Of course, as soon as it gets through the Appveyor build, I will approve it and merge it into the master branch

 

Best wishes,

 

Chris

**Comment by YoRyan** [comment]
Hmm, the build failed because this patch contains Monogame code that relies on the changes in the unstable branch.

It is therefore not possible to base it off of the master branch. We'll have to rethink our approach.

**Comment by cjakeman** [comment]
Hi Ryan,

 

I see. I should have thought of that.

 

I wonder how we have managed so far without:

 

#if MonoGame

 

 

Best wishes,

 

Chris

**Comment by YoRyan** [comment]
Will withdraw this until the Monogame port is stable.

**Pull request closed without merging**
