### PR TITLE
Manual Braking

### PR DESCRIPTION
**Pull request by peternewell**
https://blueprints.launchpad.net/or/+spec/manual-braking - Adjustments to HUD, and separation of engine and brakeman function.

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi Peter,

Looks good. Does this new feature need an entry in the Manual?

Best wishes,

Chris

**Comment by peternewell** [comment]
Hi Chris,

There are a few other changes that I would like to complete before we merge this.

I will let you know when it is ready.

Thanks

Peter

**Comment by YoRyan** [comment]
Hi Peter,

When you file a PR, you have the ability to mark it as "draft" to let us know that it's still a work-in-progress. (Unfortunately, GitHub does a pretty good job of hiding it.) I have gone ahead and done so.

Ryan

**Comment by peternewell** [comment]
Hi Ryan,
> When you file a PR, you have the ability to mark it as "draft" to let us know that it's still a work-in-progress. (Unfortunately, GitHub does a pretty good job of hiding it.) I have gone ahead and done so.

Thanks for raising this point, as it was something that I was unaware of. 

In future, could you please tell me, and then let me make the changes to the PR, rather then you making the changes for me.

In this way I will learn how to do it myself next time.

Thanks

Peter

**Review by cjakeman — APPROVED** [review]
Approved with thanks,

Chris

**Pull request merged**
