### PR TITLE
Upgrade libraries to netstandard 2.0

### PR DESCRIPTION
**Pull request by Sharpe49**
(only for libraries without Windows Forms)

### CODE REVIEW

**Comment by cesarBLG** [comment]
There are reports that TCS scripts are not compiling: http://www.elvastower.com/forums/index.php?/topic/36471-tcs-script-problems/page__pid__287979#entry287979

CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'., line: 15, column: 27

**Comment by Sharpe49** [comment]
Weird, for me it includes .Net Framework 4.7.2 during script compilation so it's still working fine...
I'll add a reference to the assembly that contains System.Enum...

**Comment by cesarBLG** [comment]
I posted my log in the forum. Your last commit didn't solve the issue (I suppose System.Object and System.Enum are in the same assembly, which was already included)

**Comment by Sharpe49** [comment]
@cesarBLG Ok, removing this commit. Seems like we will have to switch to .Net 5 directly.

**Pull request closed without merging**
