### PR TITLE
Alternate preset 3D cabviewpoints

### PR DESCRIPTION
**Pull request by Csantucci**
See TrelloBox https://trello.com/c/iDr0POSw/532-multiple-preset-viewpoints-for-3d-cabs
See also http://www.elvastower.com/forums/index.php?/topic/36339-multiple-preset-viewpoints-for-3d-cabs/page__view__findpost__p__286264

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi Carlo,

I've approved your Trello card, so any dev is free now to review, approve and merge this PR.

Thanks,
Chris

**Review by cesarBLG — APPROVED** [review]
Simple yet useful enhancement. Thanks, Carlo!

**Comment by Csantucci** [comment]
Thanks, César. Unfortunately I just had to add a further push to fix a case where switching to a rear cab only locomotive showed the first alternate cabview point instead of the rear cab. It should be OK now.

**Review by cesarBLG — APPROVED** [review]
The last commit seems OK, so I re-approve

**Comment by Csantucci** [comment]
Thanks, César

**Pull request merged**
