### PR TITLE
Update of French locales, by septf

### PR DESCRIPTION
**Pull request by Csantucci**

### CODE REVIEW

**Comment by Sharpe49** [comment]
I do not agree with some of the translations. Is there a post about that ?

**Comment by Csantucci** [comment]
There is a private conversation. I will add you to it.

**Comment by cjakeman** [comment]
So have Sharpe49's concerns (8th Feb) been addressed?

**Comment by cjakeman** [comment]
Hi Carlo, 

> There is a private conversation. I will add you to it.

Is there a resolution to this issue? The PR has been pending for a long time, so are you able to either approve or close it?

Thanks,
Chris

**Comment by Csantucci** [comment]
Hi Chris,
following your last message here I sent a reminder to Serana and septf; they agreed to discuss the issue together this just finished week. I didn't get feedbacks yet. In my opinion, if no feedback arrives within Monday evening, the PR may be approved, but not by me, because I'm the issuer.

**Comment by Csantucci** [comment]
There has been a big work by septf and I think it is worth the approval.

**Comment by Sharpe49** [comment]
We have to meet a second time and I think we will have finished the fixes.

**Comment by Sharpe49** [comment]
Here's the link for the new Pull Request which replaces this one.
https://github.com/openrails/openrails/pull/196

**Pull request merged**
