### PR TITLE
Web interface to control cab controls with external hardware

### PR DESCRIPTION
**Pull request by cesarBLG**
http://www.elvastower.com/forums/index.php?/topic/34945-web-server/page__view__findpost__p__290210
https://blueprints.launchpad.net/or/+spec/webserver-cabcontrols

Uses #717 as base, so number of changes will be huge until that is merged.

### CODE REVIEW

**Review by cjakeman — COMMENTED** [review]
Hi Cesar

This looks really good and I'll approve it as soon as #717 is merged.

Also discussed it with James.

I like the neat way you have piggy-backed onto the RailDriver mechanism.

At some point we might want to extend this, so it does more than CabControls (e.g. control the camera or make a Save operation).

Also might want to unify this (and the RailDriver) with keyboard commands so all changes are recorded in the Replay mechanism.

That's for later, of course, not a criticism of your work here. Let's see if HTTP POST is fast enough for our users.

Best wishes,

Chris

**Comment by Csantucci** [comment]
César,
your fix for 3D cabs does not compile, because you first define renderer and then define it again as argument of TryGetValue.

**Comment by cesarBLG** [comment]
Thanks for informing about it. It seems the syntax highlighting failed. Now it's compiling.

**Comment by twpol** [comment]
Just want to alert people that this _might_ be causing this issue - I have asked Traindude to test the Unstable Version U2023.01.20-0206 from just before this PR to verify:

- http://www.elvastower.com/forums/index.php?/topic/36869-raildriver-stopped-working-after-u20230122-0351/page__view__findpost__p__293510
- http://www.elvastower.com/forums/index.php?/topic/36865-raildriver-not-working/page__view__findpost__p__293432

**Comment by cesarBLG** [comment]
Hi James,
Traindude provided the key information here: http://www.elvastower.com/forums/index.php?/topic/24040-3d-cabs/page__view__findpost__p__294295
The problem only happened on locomotives with a 3D cab but with no 2D cab. This should have been solved with the latest commits.

**Comment by twpol** [comment]
> Hi James, Traindude provided the key information here: http://www.elvastower.com/forums/index.php?/topic/24040-3d-cabs/page__view__findpost__p__294295 The problem only happened on locomotives with a 3D cab but with no 2D cab. This should have been solved with the latest commits.

Okay, thanks, I've let them know (they contacted me in private and did not mention that post)

**Comment by cesarBLG** [comment]
@cjakeman I don't think there are more undesired effects with this PR, so in principle it can be merged. There are some minor problems related to a couple of raildriver buttons, but those are solved in #757

**Review by cjakeman — APPROVED** [review]
Hi Cesar,

All checked - nice work.

Approved with thanks,

Chris

**Pull request merged**
