### PR TITLE
Distributed power american style. Blueprint https://blueprints.launchpad.net/or/+spec/distributed-power

### PR DESCRIPTION
**Pull request by Csantucci**
With the agreement of the original developer Peter Gulyas.

### CODE REVIEW

**Review by pzgulyas — APPROVED** [review]
I don't know how ethical reviewing mostly my own code, but I give you a like (approve) to this PR. :-)

**Comment by Csantucci** [comment]
> I don't know how ethical reviewing mostly my own code, but I give you a like (approve) to this PR. :-)

Thanks Peter! You were faster than I thought! I'm adding to the PR also the correction of a bug (see http://www.elvastower.com/forums/index.php?/topic/26249-remote-control-dpu-units/page__view__findpost__p__278747 ) and also the DPU Info Window, that wasn't added up to now to get feedback from the community. So, when this will be added, I'll kindly ask you to approve the PR again :)

**Comment by Csantucci** [comment]
I have now updated code and documentation, and am ready again for review.

**Review by pzgulyas — APPROVED** [review]
It still looks all right to me.

**Comment by Csantucci** [comment]
> It still looks all right to me.

Thanks Peter!

**Pull request merged**
