### PR TITLE
No speed update

### PR DESCRIPTION
**Pull request by Roeterdink**
Add signal aspect parameter **or_nospeedupdate** to signal configuration, see thread : 
https://www.elvastower.com/forums/index.php?/topic/37573-proposed-new-signal-aspect-parameter-or-nospeedupdate/page__view__findpost__p__302320

### CODE REVIEW

**Review by Csantucci — DISMISSED** [review]
That's OK to me, thanks for the feature. I don't know if you must have an approved Trello card or blueprint to merge it.

**Comment by Roeterdink** [comment]
Thanks. As far as I know, a reference to a thread in Elvas Tower is also a valid reference.

**Comment by Csantucci** [comment]
> Thanks. As far as I know, a reference to a thread in Elvas Tower is also a valid reference.

Hi Rob, AFAIK this for sure does not apply to major enhancements. Maybe it could apply to enhancements like this one.
By the way  a short description of the feature and its syntax in the OR manual would be welcome.

**Comment by cjakeman** [comment]
> That's OK to me, thanks for the feature. I don't know if you must have an approved Trello card or blueprint to merge it.

Yes, enhancements and new features require a Trello Card or a Blueprint which has been approved. A single ard can cover a number of related improvements as in this series of PRs. Please create a card for this series, so I can approve it.

**Comment by Csantucci** [comment]
Hi Rob,
please take note of this https://www.elvastower.com/forums/index.php?/topic/32640-or-newyear-mg/page__view__findpost__p__302626 , which occurs also in the Unstable release, see here https://www.elvastower.com/forums/index.php?/topic/32640-or-newyear-mg/page__view__findpost__p__302643 .

**Comment by Roeterdink** [comment]
Can the merge be undone?
This needs checking out and I do not have time for that at the moment. If it can be withdrawn, I will make a new pull request at a later dat.

**Comment by Csantucci** [comment]
> Can the merge be undone? This needs checking out and I do not have time for that at the moment. If it can be withdrawn, I will make a new pull request at a later dat.

Clicking on "Close pull request" at the bottom of the page should do the job

**Pull request closed without merging**
