### PR TITLE
Mark particle drawer texture for wagons

### PR DESCRIPTION
**Pull request by Sharpe49**
Should fix : http://www.elvastower.com/forums/index.php?/topic/29799-steam-effects-for-diesel-locomotives-and-passenger-cars/page__view__findpost__p__286963

### CODE REVIEW

**Comment by cjakeman** [comment]
Hi Cedric,

This looks like a very simple and effective change.

I'll leave it for Peter to check that it works on his test cases.

Many thanks,

Chris

**Comment by peternewell** [comment]
> I'll leave it for Peter to check that it works on his test cases.

It appears that the Unstable version has stopped building as the last build was on 26/07, so this correction hasn't made it through to the Unstable version. When the build starts again, I can check it.

Peter

**Review by peternewell — APPROVED** [review]
This patch seems to have fixed the bug, so I have approved it.

Is this a universal fix for all textures? Does there need to be some developer notes for any future issues detected or new features added?

Thanks

**Comment by cjakeman** [comment]
> Is this a universal fix for all textures? Does there need to be some developer notes for any future issues detected or new features added?

Not for all textures, but for all ParticleEmitters. These are now handled in the MSTSWagonViewer instead of the MSTSLocomotiveViewer, which makes lots of sense. Why didn't I think of that?

Yes, we could do with some documentation or helpful comments, especially since textures and shapes are managed differently.

Thanks to Cedric for sorting this.

**Pull request merged**
