### PR TITLE
Revised installer for Release 1.4

### PR DESCRIPTION
**Pull request by cjakeman**
Prerequisite .NET 3.5 => 4.7.2
Prerequisite XNA dropped
Updated "README.txt" and "Using the installer scripts.txt"
Dropped option to install from DVD

### CODE REVIEW

**Comment by cjakeman** [comment]
Not ready yet as check for and install of .NET 4.7.2 not working correctly.

**Comment by cjakeman** [comment]
Updates to Build.cmd have still to be checked.

**Comment by cjakeman** [comment]
CLR20r3 Event error when installing on Windows 7 SP1 (i.e. The installation succeeded and Menu.exe runs but RunActivity.exe fails).
Installs and runs fine on Windows 10.

**Comment by twpol** [comment]
Fixed the conflicts in `Build.cmd` and validated that they're all good 👍

**Comment by cjakeman** [comment]
Not much point specifiying the pre-requisites for installation in the final Readme text (although it's always been this way).
Inno Setup has an InfoAfterFile and an InnoBeforeFile, so I moved the text for Installation Prerequisites out of Source\Runactivity\Readme.txt into Source\RunActivity\Prerequisites.txt.

**Review by twpol — APPROVED** [review]

**Pull request merged**
